#!/bin/bash

# cria o usuario que usara o BD
psql postgres -c "CREATE USER planteiAdmin WITH ENCRYPTED PASSWORD 'planteiAdmin';"

# cria o BD 'plantei'
psql postgres -c "CREATE DATABASE plantei WITH 
                    OWNER = planteiAdmin
                    ENCODING = 'UTF8'
                    TABLESPACE = pg_default
                    CONNECTION LIMIT = -1;"

# Da acesso total do usuario criado anteriormente no BD 'plantei'
psql postgres -c "GRANT ALL PRIVILEGES ON DATABASE plantei TO planteiAdmin;"
